### ISSUE TITLE
Errai - RichEditor - popup closes immediately

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material-demo-errai#1]
It seems that using Dependency Injection, the getElement() method returns null.
So what happens to the richeditor, it closes the popup immediately.

**Comment by kevzlou7979** [comment]
With the prior test, it turns out that Injection on Errai calls onLoad twice. See provided screenshot
![image](https://cloud.githubusercontent.com/assets/3138071/18205621/871de24c-7155-11e6-9b3a-38e290801551.png)

**Comment by BenDol** [comment]
Yea, we need to ensure all widgets can have onLoad called multiple times functionally.

**Comment by kevzlou7979** [comment]
The solution ive got is instead of using `getElement()` as parameter in jquery selector , we will use a autogenerated Id instead. Which will work well on RichEditor.

**Comment by BenDol** [comment]
There should be a better solution for this. Will investigate it.

**Comment by BenDol** [comment]
Fixed here https://github.com/GwtMaterialDesign/gwt-material-addins/commit/3f790a8db526ad14affe39b68bf20b7914265807

**Comment by kevzlou7979** [comment]
Ok tested and working great
