### ISSUE TITLE
Archetype not working

### ISSUE THREAD

**Issue by elnicko** [GwtMaterialDesign/gwt-material-demo-errai#16]
Sorry to bother you, but I'd like to get some assistance on starting a project with your awesome demo. I see that you provided the following command to start a new project via a maven archetype:

`mvn archetype:generate -DarchetypeGroupId=com.github.gwtmaterialdesign -DarchetypeArtifactId=gwt-material-errai-archetype -DarchetypeRepository=https://oss.sonatype.org/content/repositories/snapshots/ -DarchetypeVersion=1.0-SNAPSHOT`

This fails on my machine with the following:

`The desired archetype does not exist (com.github.gwtmaterialdesign:gwt-material-errai-archetype:1.0-SNAPSHOT)`

Any hints are greatly appreciated.

**Comment by kevzlou7979** [comment]
Hi there, try to clone this project first and then run mvn install. We don't provide this to Maven as this is just a demo project. I will update the README instead.

**Comment by kevzlou7979** [comment]
You can do the latest release instead of that snapshot. 
```
mvn archetype:generate -DarchetypeGroupId=com.github.gwtmaterialdesign -DarchetypeArtifactId=gwt-material-errai-archetype -DarchetypeVersion=2.0
```

**Comment by marabangath** [comment]
> You can do the latest release instead of that snapshot.
> 
> ```
> mvn archetype:generate -DarchetypeGroupId=com.github.gwtmaterialdesign -DarchetypeArtifactId=gwt-material-errai-archetype -DarchetypeVersion=2.0
> ```

Works for me on the same issue. Thanks!
