### ISSUE TITLE
Could you please fix the build?

### ISSUE THREAD

**Issue by ghost** [GwtMaterialDesign/gwt-material-demo-errai#4]
Fresh checkout, mvn clean install:

[INFO] 27 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.362s
[INFO] Finished at: Thu Sep 08 09:52:42 EDT 2016
[INFO] Final Memory: 40M/489M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project gwt-material-demo-errai: Compilation failure: Compilation failure:
[ERROR] /home/valter/Projects/wds/gwt-material-demo-errai/src/main/java/gwt/material/demo/errai/client/local/page/addins/AutocompletePage.java:[65,11] error: cannot access AbstractValueWidget
[ERROR] class file for gwt.material.design.client.base.AbstractValueWidget not found
[ERROR] /home/valter/Projects/wds/gwt-material-demo-errai/src/main/java/gwt/material/demo/errai/client/local/page/addins/AutocompletePage.java:[68,15] error: no suitable method found for add(MaterialAutoComplete)
[ERROR] method Panel.add(Widget) is not applicable
[ERROR](argument mismatch; MaterialAutoComplete cannot be converted to Widget)
[ERROR] method Panel.add(IsWidget) is not applicable
[ERROR](argument mismatch; MaterialAutoComplete cannot be converted to IsWidget)
[ERROR] method MaterialWidget.add(Widget) is not applicable
[ERROR](argument mismatch; MaterialAutoComplete cannot be converted to Widget)
[ERROR] /home/valter/Projects/wds/gwt-material-demo-errai/src/main/java/gwt/material/demo/errai/client/local/page/addins/AutocompletePage.java:[72,17] error: cannot find symbol
[ERROR] symbol:   method open()
[ERROR] location: variable modal of type MaterialModal
[ERROR] /home/valter/Projects/wds/gwt-material-demo-errai/src/main/java/gwt/material/demo/errai/client/local/page/addins/StepperPage.java:[74,16] error: cannot find symbol
[ERROR] ); })
[ERROR] location: variable stepper6 of type MaterialStepper
[ERROR] /home/valter/Projects/wds/gwt-material-demo-errai/src/main/java/gwt/material/demo/errai/client/local/page/addins/StepperPage.java:[83,16] error: cannot find symbol
[ERROR] ); })
[ERROR] location: variable stepper5 of type MaterialStepper
[ERROR] /home/valter/Projects/wds/gwt-material-demo-errai/src/main/java/gwt/material/demo/errai/client/local/page/addins/StepperPage.java:[92,16] error: cannot find symbol
[ERROR] ); })
[ERROR] location: variable stepper4 of type MaterialStepper
[ERROR] /home/valter/Projects/wds/gwt-material-demo-errai/src/main/java/gwt/material/demo/errai/client/local/page/addins/StepperPage.java:[96,16] error: cannot find symbol
[ERROR] ); })
[ERROR] location: variable stepper4 of type MaterialStepper
[ERROR] /home/valter/Projects/wds/gwt-material-demo-errai/src/main/java/gwt/material/demo/errai/client/local/page/addins/StepperPage.java:[100,16] error: cannot find symbol
[ERROR] ); })
[ERROR] location: variable stepper4 of type MaterialStepper
[ERROR] /home/valter/Projects/wds/gwt-material-demo-errai/src/main/java/gwt/material/demo/errai/client/local/page/addins/StepperPage.java:[104,16] error: cannot find symbol
[ERROR] ); })
[ERROR] location: variable stepper4 of type MaterialStepper
[ERROR] /home/valter/Projects/wds/gwt-material-demo-errai/src/main/java/gwt/material/demo/errai/client/local/page/addins/StepperPage.java:[114,17] error: cannot find symbol
[ERROR] symbol:   method open()
[ERROR] location: variable modal of type MaterialModal
[ERROR] /home/valter/Projects/wds/gwt-material-demo-errai/src/main/java/gwt/material/demo/errai/client/local/page/addins/StepperPage.java:[116,16] error: cannot find symbol
[ERROR] ); })
[ERROR] location: variable stepper3 of type MaterialStepper
[ERROR] /home/valter/Projects/wds/gwt-material-demo-errai/src/main/java/gwt/material/demo/errai/client/local/page/addins/StepperPage.java:[118,17] error: cannot find symbol
[ERROR] symbol:   method close()
[ERROR] location: variable modal of type MaterialModal
[ERROR] /home/valter/Projects/wds/gwt-material-demo-errai/src/main/java/gwt/material/demo/errai/client/local/page/addins/StepperPage.java:[129,16] error: cannot find symbol
[ERROR] ); })
[ERROR] location: variable stepper2 of type MaterialStepper
[ERROR] /home/valter/Projects/wds/gwt-material-demo-errai/src/main/java/gwt/material/demo/errai/client/local/page/addins/StepperPage.java:[138,15] error: cannot find symbol
[ERROR] ); })
[ERROR] location: variable stepper of type MaterialStepper
[ERROR] /home/valter/Projects/wds/gwt-material-demo-errai/src/main/java/gwt/material/demo/errai/client/local/page/addins/RichEditorPage.java:[77,13] error: cannot find symbol
[ERROR] symbol:   method setHeight(String)
[ERROR] location: variable rich7 of type MaterialRichEditor
[ERROR] /home/valter/Projects/wds/gwt-material-demo-errai/src/main/java/gwt/material/demo/errai/client/local/page/addins/RichEditorPage.java:[78,13] error: cannot find symbol
[ERROR] ); })
[ERROR] location: variable rich7 of type MaterialRichEditor
[ERROR] /home/valter/Projects/wds/gwt-material-demo-errai/src/main/java/gwt/material/demo/errai/client/local/page/addins/RichEditorPage.java:[82,13] error: cannot find symbol
[ERROR] ); })
[ERROR] location: variable rich7 of type MaterialRichEditor
[ERROR] /home/valter/Projects/wds/gwt-material-demo-errai/src/main/java/gwt/material/demo/errai/client/local/page/addins/RichEditorPage.java:[86,13] error: cannot find symbol
[ERROR] ); })
[ERROR] location: variable rich7 of type MaterialRichEditor
[ERROR] /home/valter/Projects/wds/gwt-material-demo-errai/src/main/java/gwt/material/demo/errai/client/local/page/addins/RichEditorPage.java:[90,13] error: cannot find symbol
[ERROR] ); })
[ERROR] location: variable rich7 of type MaterialRichEditor
[ERROR] /home/valter/Projects/wds/gwt-material-demo-errai/src/main/java/gwt/material/demo/errai/client/local/page/addins/RichEditorPage.java:[94,13] error: cannot find symbol
[ERROR] ); })
[ERROR] location: variable rich7 of type MaterialRichEditor
[ERROR] /home/valter/Projects/wds/gwt-material-demo-errai/src/main/java/gwt/material/demo/errai/client/local/page/addins/RichEditorPage.java:[104,13] error: cannot find symbol
[ERROR] symbol:   method setHeight(String)
[ERROR] location: variable rich6 of type MaterialRichEditor
[ERROR] /home/valter/Projects/wds/gwt-material-demo-errai/src/main/java/gwt/material/demo/errai/client/local/page/addins/RichEditorPage.java:[117,13] error: cannot find symbol
[ERROR] symbol:   method setHeight(String)
[ERROR] location: variable rich5 of type MaterialRichEditor
[ERROR] /home/valter/Projects/wds/gwt-material-demo-errai/src/main/java/gwt/material/demo/errai/client/local/page/addins/RichEditorPage.java:[126,13] error: cannot find symbol
[ERROR] symbol:   method setHeight(String)
[ERROR] location: variable rich4 of type MaterialRichEditor
[ERROR] /home/valter/Projects/wds/gwt-material-demo-errai/src/main/java/gwt/material/demo/errai/client/local/page/addins/ComboBoxPage.java:[154,20] error: no suitable method found for add(MaterialComboBox<State>)
[ERROR] method Panel.add(Widget) is not applicable
[ERROR](argument mismatch; MaterialComboBox<State> cannot be converted to Widget)
[ERROR] method Panel.add(IsWidget) is not applicable
[ERROR](argument mismatch; MaterialComboBox<State> cannot be converted to IsWidget)
[ERROR] method MaterialWidget.add(Widget) is not applicable
[ERROR](argument mismatch; MaterialComboBox<State> cannot be converted to Widget)
[ERROR] /home/valter/Projects/wds/gwt-material-demo-errai/src/main/java/gwt/material/demo/errai/client/local/page/addins/ComboBoxPage.java:[158,17] error: cannot find symbol
[ERROR] symbol:   method open()
[ERROR] location: variable modal of type MaterialModal
[ERROR] /home/valter/Projects/wds/gwt-material-demo-errai/src/main/java/gwt/material/demo/errai/client/local/page/addins/ComboBoxPage.java:[266,14] error: cannot find symbol
[ERROR] ); })
[ERROR] location: variable combo9 of type MaterialComboBox<State>
[ERROR] /home/valter/Projects/wds/gwt-material-demo-errai/src/main/java/gwt/material/demo/errai/client/local/page/addins/ComboBoxPage.java:[273,15] error: cannot find symbol
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by kevzlou7979** [comment]
@systemv This project is still ongoing dev. As we are testing each component to support errai.

**Comment by ghost** [comment]
Thank you, I know, but this is too good and I cant wait to start experimenting with it. Amazing work!
